site_name: Public Philosophy (Economics Perspective)
site_url: https://tsuyoshi-adachi.github.io/Normative-Political-Economy-Economic-Perspective/
nav:
  - "Home": "index.md"
  - "Part I: Measure Welfare":
      - "01 Welfarism Equilibrium": "01_welfarism_equilibrium.md"
      - "02 Subjective Welfare Principle": "02-subjective-welfare-principle.md"
      - "03 Review of Surplus": "03-review-of-surplus.md"
      - "04 Maximizing Total Surplus": "04_maximizing_total_surplus.md"
      - "05 Second Best Commodity Taxation": "05_second_best_commodity_taxation.md"
      - "06 Second Best Income Tax": "06_second_best_income_tax.md"
      - "07 Maximizing Total Surplus Summary": "07_maximizing_total_surplus_summary.md"
      - "08 Money Not Source of Value": "08_money_not_source_of_value.md"
      - "09 Welfare Real Income": "09_welfare_real_income.md"
      - "10 WTP Income Effect": "10_wtp_income_effect.md"
      - "11 Informational Content Welfare Measures": "11_informational_content_welfare_measures.md"
      - "12 Capability Approach": "12_capability_approach.md"
      - "13 Subjective Wellbeing Dashboard": "13_subjective_wellbeing_dashboard.md"
      - "14 Nudge Soft Paternalism": "14_nudge_soft_paternalism.md"
  - "Part II: Evaluate Distributions":
      - "15 Welfare Distribution Economics as Science": "15_welfare_distribution_economics_as_science.md"
      - "16 Equilibrium Welfare Tradeoff Efficiency Equality": "16_equilibrium_welfare_tradeoff_efficiency_equality.md"
      - "17 Social Welfare Functions": "17_social_welfare_functions.md"
      - "18 Examples Social Welfare Functions": "18_examples_social_welfare_functions.md"
      - "19 Cautions Division of Labor": "19_cautions_division_of_labor.md"
      - "20 Harsanyi Social Welfare Function": "20_harsanyi_social_welfare_function.md"
      - "21 Lorenz Curve": "21_lorenz_curve.md"
      - "22 Pigou Dalton Transfer Principle": "22_pigou_dalton_transfer_principle.md"
      - "23 Comparing Inequality": "23_comparing_inequality.md"
      - "24 Poverty Sufficientarianism": "24_poverty_sufficientarianism.md"
      - "25 Welfare Evaluation Uncertainty": "25_welfare_evaluation_uncertainty.md"
      - "26 Intergenerational Equity Social Welfare Functions": "26_intergenerational_equity_social_welfare_functions.md"
      - "27 Population Ethics Social Welfare Functions": "27_population_ethics_social_welfare_functions.md"
  - "Parts III & IV: Designing Voting and Fair Allocations":
      - "28 Thinking Voting Methods": "28_Thinking_Voting_Methods.md"
      - "29 Borda Count": "29_Borda_Count.md"
      - "30 Approval Voting": "30_Approval_Voting.md"
      - "31 Fascinating Rules": "31_Fascinating_Rules.md"
      - "32 Rationality Preference": "32_Rationality_Preference.md"
      - "33 Social Choice Rules": "33_Social_Choice_Rules.md"
      - "34 Strategy Proofness": "34_Strategy_Proofness.md"
      - "35 Spoiler VoteSplitting Problem": "35_Spoiler_VoteSplitting_Problem.md"
      - "36 Pairwise Majority Condorcet": "36_Pairwise_Majority_Condorcet.md"
      - "37 Median Voter Rule": "37_Median_Voter_Rule.md"
      - "38 Condorcet Jury Theorem": "38_Condorcet_Jury_Theorem.md"
      - "39 Judgment Paradox": "39_Judgment_Paradox.md"
      - "40 Envy Freeness": "40_Envy_Freeness.md"
      - "41 Core Stability": "41_Core_Stability.md"
      - "42 Market Fairness": "42_Market_Fairness.md"
      - "43 Market Design": "43_Market_Design.md"
      - "44 Carbon Pie": "44_Carbon_Pie.md"
      - "45 Equal Opportunity": "45_Equal_Opportunity.md"
theme:
  name: material
  logo: assets/PP.png
  favicon: assets/favicon.ico

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
