---
site_name: Public Philosophy (Economics Perspective)
site_url: https://tsuyoshi-adachi.github.io/Normative-Political-Economy-Economic-Perspective/
nav:
  - "Part I: Measure Welfare":
      - "01 Welfarism Equilibrium": "01_welfarism_equilibrium.md"
      - "02 Subjective Welfare Principle": "02-subjective-welfare-principle.md"
      - "03 Review of Surplus": "03-review-of-surplus.md"
      - "04 Maximizing Total Surplus": "04_maximizing_total_surplus.md"
      - "05 Second Best Commodity Taxation": "05_second_best_commodity_taxation.md"
      - "06 Second Best Income Tax": "06_second_best_income_tax.md"
      - "07 Maximizing Total Surplus Summary": "07_maximizing_total_surplus_summary.md"
      - "08 Money Not Source of Value": "08_money_not_source_of_value.md"
      - "09 Welfare Real Income": "09_welfare_real_income.md"
      - "10 WTP Income Effect": "10_wtp_income_effect.md"
      - "11 Informational Content Welfare Measures": "11_informational_content_welfare_measures.md"
      - "12 Capability Approach": "12_capability_approach.md"
      - "13 Subjective Wellbeing Dashboard": "13_subjective_wellbeing_dashboard.md"
      - "14 Nudge Soft Paternalism": "14_nudge_soft_paternalism.md"
  - "Part II: Evaluate Distributions":
      - "15 Welfare Distribution Economics as Science": "15_welfare_distribution_economics_as_science.md"
      - "16 Equilibrium Welfare Tradeoff Efficiency Equality": "16_equilibrium_welfare_tradeoff_efficiency_equality.md"
      - "17 Social Welfare Functions": "17_social_welfare_functions.md"
      - "18 Examples Social Welfare Functions": "18_examples_social_welfare_functions.md"
      - "19 Cautions Division of Labor": "19_cautions_division_of_labor.md"
      - "20 Harsanyi Social Welfare Function": "20_harsanyi_social_welfare_function.md"
      - "21 Lorenz Curve": "21_lorenz_curve.md"
      - "22 Pigou Dalton Transfer Principle": "22_pigou_dalton_transfer_principle.md"
      - "23 Comparing Inequality": "23_comparing_inequality.md"
      - "24 Poverty Sufficientarianism": "24_poverty_sufficientarianism.md"
      - "25 Welfare Evaluation Uncertainty": "25_welfare_evaluation_uncertainty.md"
      - "26 Intergenerational Equity Social Welfare Functions": "26_intergenerational_equity_social_welfare_functions.md"
      - "27 Population Ethics Social Welfare Functions": "27_population_ethics_social_welfare_functions.md"
theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

